In [3]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

In [4]:
df_house16 = pd.read_csv('../data/properties_2016.csv')
df_train16 = pd.read_csv('../data/train_2016_v2.csv')
# df_merge16 = pd.merge(df_house16, df_train16, on='parcelid')

df_house17 = pd.read_csv('../data/properties_2017.csv')
df_train17 = pd.read_csv('../data/train_2017.csv')
#df_merge17 = pd.merge(df_house17, df_train17, on='parcelid')

/Users/haenalee/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/haenalee/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
# Read the property data
#df_house16 = pd.read_csv('../data/properties_2016.csv', na_values=['NA'])
property_data_2016 = df_house16
#print(property_data_2016.shape) # Total size : (2985217, 58)

df_house17 = pd.read_csv('../data/properties_2017.csv', na_values=['NA'])
property_data_2017 = df_house17
#print(property_data_2017.shape) # Total size : (2985217, 58)

/Users/haenalee/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/haenalee/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
property_data_2016.head()
#property_data_2016.describe()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [7]:
property_data_2017.head()
#property_data_2017.describe()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,...,1.0,NaN,660680.0,1434941.0,2016.0,774261.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,6.0,NaN,NaN,...,1.0,NaN,580059.0,1174475.0,2016.0,594416.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,1.0,NaN,196751.0,440101.0,2016.0,243350.0,5725.17,NaN,NaN,NaN

In [8]:
# Temporary #

#df = property_data_2016.dropna()
#print(df.shape)

#df = property_data_2017.dropna()
#print(df.shape)

df = np.where(property_data_2016 != property_data_2017)
df

(array([      0,       0,       0, ..., 2985216, 2985216, 2985216]),
 array([ 1,  2,  3, ..., 55, 56, 57]))

In [9]:
# Temporary #
feature_names = pd.DataFrame(property_data_2017.columns)

feature_names.columns = [
    'Feature'
]

feature_names

                         Feature
0                       parcelid
1          airconditioningtypeid
2       architecturalstyletypeid
3                   basementsqft
4                    bathroomcnt
5                     bedroomcnt
6            buildingclasstypeid
7          buildingqualitytypeid
8              calculatedbathnbr
9                     decktypeid
10      finishedfloor1squarefeet
11  calculatedfinishedsquarefeet
12          finishedsquarefeet12
13          finishedsquarefeet13
14          finishedsquarefeet15
15          finishedsquarefeet50
16           finishedsquarefeet6
17                          fips
18                  fireplacecnt
19                   fullbathcnt
20                  garagecarcnt
21               garagetotalsqft
22                hashottuborspa
23         heatingorsystemtypeid
24                      latitude
25                     longitude
26             lotsizesquarefeet
27                       poolcnt
28                   poolsizesum
29                  pooltypeid10
30                   pooltypeid2
31                   pooltypeid7
32     propertycountylandusecode
33         propertylandusetypeid
34            propertyzoningdesc
35        rawcensustractandblock
36                  regionidcity
37                regionidcounty
38          regionidneighborhood
39                   regionidzip
40                       roomcnt
41                   storytypeid
42           threequarterbathnbr
43        typeconstructiontypeid
44                       unitcnt
45            yardbuildingsqft17
46            yardbuildingsqft26
47                     yearbuilt
48               numberofstories
49                 fireplaceflag
50    structuretaxvaluedollarcnt
51             taxvaluedollarcnt
52                assessmentyear
53         landtaxvaluedollarcnt
54                     taxamount
55            taxdelinquencyflag
56            taxdelinquencyyear
57           censustractandblock

In [10]:
# Feature 0 ~ Feature 17
property_data_2017.loc[:, 'parcelid':'fips'].describe()
#property_data_2017.describe()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,finishedsquarefeet6,fips
count,2.985217e+06,815362.000000,6061.000000,1627.000000,2.982260e+06,2.982272e+06,12731.000000,1.941395e+06,2.868061e+06,17379.0,203758.000000,2.940120e+06,2.720786e+06,7671.000000,190185.000000,203758.000000,21482.000000,2.982285e+06
mean,1.332586e+07,1.945723,7.202607,647.220652,2.216196e+00,3.093362e+00,3.734742,6.280822e+00,2.303826e+00,66.0,1379.780460,1.831455e+03,1.764045e+03,1178.916699,2754.869233,1392.029093,2427.555209,6.048053e+03
std,7.909966e+06,3.160507,2.436290,538.787104,1.078250e+00,1.271569e+00,0.500371,1.729923e+00,1.003243e+00,0.0,634.422849,1.954198e+03,1.031383e+03,357.093554,5999.380115,682.323851,7786.185183,2.024082e+01
min,1.071172e+07,1.000000,2.000000,20.000000,0.000000e+00,0.000000e+00,1.000000,1.000000e+00,1.000000e+00,66.0,1.000000,1.000000e+00,1.000000e+00,120.000000,112.000000,3.000000,117.000000,6.037000e+03
25%,1.164371e+07,1.000000,7.000000,272.000000,2.000000e+00,2.000000e+00,3.000000,5.000000e+00,2.000000e+00,66.0,1010.000000,1.215000e+03,1.198000e+03,960.000000,1696.000000,1012.000000,1072.000000,6.037000e+03
50%,1.254509e+07,1.000000,7.000000,535.000000,2.000000e+00,3.000000e+00,4.000000,6.000000e+00,2.000000e+00,66.0,1281.000000,1.574000e+03,1.542000e+03,1296.000000,2173.000000,1284.000000,2008.000000,6.037000e+03
75%,1.409712e+07,1.000000,7.000000,847.500000,3.000000e+00,4.000000e+00,4.000000,8.000000e+00,3.000000e+00,66.0,1615.000000,2.140000e+03,2.075000e+03,1440.000000,2975.000000,1619.000000,3411.000000,6.059000e+03
max,1.696019e+08,13.000000,27.000000,8516.000000,3.200000e+01,2.500000e+01,5.000000,1.200000e+01,3.200000e+01,66.0,31303.000000,9.525760e+05,4.270790e+05,2688.000000,820242.000000,41906.000000,952576.000000,6.111000e+03

In [11]:
# Feature 18 ~ Feature 35
property_data_2017.loc[:, 'fireplacecnt':'rawcensustractandblock'].describe()
#property_data_2017.describe()

,fireplacecnt,fullbathcnt,garagecarcnt,garagetotalsqft,heatingorsystemtypeid,latitude,longitude,lotsizesquarefeet,poolcnt,poolsizesum,pooltypeid10,pooltypeid2,pooltypeid7,propertylandusetypeid,rawcensustractandblock
count,313124.000000,2.868061e+06,891008.000000,891008.00000,1.869164e+06,2.982285e+06,2.982285e+06,2.712511e+06,539632.0,27958.000000,17006.0,33056.0,505895.0,2.982285e+06,2.982285e+06
mean,1.168959,2.248089e+00,1.826581,383.15622,4.083750e+00,3.400131e+07,-1.182017e+08,2.260376e+04,1.0,519.715430,1.0,1.0,1.0,2.600508e+02,6.048367e+07
std,0.461855,9.929959e-01,0.608934,246.21942,3.286780e+00,2.435157e+05,3.455918e+05,2.499836e+05,0.0,191.325869,0.0,0.0,0.0,1.593121e+01,2.008914e+05
min,1.000000,1.000000e+00,0.000000,0.00000,1.000000e+00,3.332439e+07,-1.194758e+08,1.000000e+02,1.0,19.000000,1.0,1.0,1.0,3.100000e+01,6.037101e+07
25%,1.000000,2.000000e+00,2.000000,312.00000,2.000000e+00,3.382740e+07,-1.183929e+08,5.683000e+03,1.0,430.000000,1.0,1.0,1.0,2.610000e+02,6.037400e+07
50%,1.000000,2.000000e+00,2.000000,441.00000,2.000000e+00,3.400807e+07,-1.181721e+08,7.000000e+03,1.0,495.000000,1.0,1.0,1.0,2.610000e+02,6.037571e+07
75%,1.000000,3.000000e+00,2.000000,494.00000,7.000000e+00,3.416186e+07,-1.179489e+08,9.893000e+03,1.0,594.000000,1.0,1.0,1.0,2.610000e+02,6.059042e+07
max,9.000000,3.200000e+01,25.000000,7749.00000,2.400000e+01,3.481965e+07,-1.175543e+08,3.710005e+08,1.0,17410.000000,1.0,1.0,1.0,2.790000e+02,6.111009e+07

In [12]:
# Feature 36 ~ Feature 57
property_data_2017.loc[:, 'regionidcity':'censustractandblock'].describe()
#property_data_2017.describe()

,regionidcity,regionidcounty,regionidneighborhood,regionidzip,roomcnt,storytypeid,threequarterbathnbr,typeconstructiontypeid,unitcnt,yardbuildingsqft17,yardbuildingsqft26,yearbuilt,numberofstories,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyyear,censustractandblock
count,2.923089e+06,2.982285e+06,1.156741e+06,2.972503e+06,2.982248e+06,1623.0,316357.000000,6746.000000,1.981042e+06,81588.000000,2646.000000,2.937384e+06,685676.000000,2.938753e+06,2.950951e+06,2.982284e+06,2.925291e+06,2.962465e+06,56517.000000,2.910232e+06
mean,3.498766e+04,2.569085e+03,1.935387e+05,9.655329e+04,1.474357e+00,7.0,1.010611,5.999555,1.180303e+00,321.541612,278.365457,1.964438e+03,1.400956,1.781429e+05,4.435279e+05,2.015998e+03,2.684558e+05,5.408949e+03,13.891696,6.048434e+13
std,5.070968e+04,7.886840e+02,1.657253e+05,3.680815e+03,2.839869e+00,0.0,0.120602,0.384079,2.486949e+00,236.884782,369.784399,2.364428e+01,0.539056,4.600503e+05,8.163366e+05,6.039949e-02,4.865097e+05,9.675567e+03,2.562172,3.249133e+11
min,3.491000e+03,1.286000e+03,6.952000e+03,9.598200e+04,0.000000e+00,7.0,1.000000,4.000000,1.000000e+00,10.000000,10.000000,1.801000e+03,1.000000,1.000000e+00,1.000000e+00,2.000000e+03,1.000000e+00,2.400000e-01,0.000000,-1.000000e+00
25%,1.244700e+04,1.286000e+03,4.673600e+04,9.618000e+04,0.000000e+00,7.0,1.000000,6.000000,1.000000e+00,190.000000,96.000000,1.950000e+03,1.000000,7.766600e+04,1.882200e+05,2.016000e+03,7.970000e+04,2.468620e+03,14.000000,6.037400e+13
50%,2.521800e+04,3.101000e+03,1.189200e+05,9.637700e+04,0.000000e+00,7.0,1.000000,6.000000,1.000000e+00,270.000000,168.000000,1.963000e+03,1.000000,1.270660e+05,3.211610e+05,2.016000e+03,1.766190e+05,4.007620e+03,14.000000,6.037572e+13
75%,4.545700e+04,3.101000e+03,2.748000e+05,9.697400e+04,0.000000e+00,7.0,1.000000,6.000000,1.000000e+00,390.000000,320.000000,1.981000e+03,2.000000,2.040000e+05,5.140720e+05,2.016000e+03,3.261000e+05,6.230500e+03,15.000000,6.059042e+13
max,3.965560e+05,3.101000e+03,7.641670e+05,3.996750e+05,9.600000e+01,7.0,7.000000,13.000000,9.970000e+02,7983.000000,6141.000000,2.016000e+03,41.000000,2.553212e+08,3.196225e+08,2.016000e+03,9.401108e+07,3.823176e+06,99.000000,4.830301e+14

In [13]:
# Extract the features to analyze
feature_list = ['parcelid','bedroomcnt','buildingqualitytypeid',
                'calculatedbathnbr','calculatedfinishedsquarefeet',
                'latitude','longitude','lotsizesquarefeet',#'roomcnt',
                'yearbuilt','structuretaxvaluedollarcnt']
# 'landtaxvaluedollarcnt','taxamount'

feature_data_2016 = property_data_2016[feature_list]
feature_data_2017 = property_data_2017[feature_list]

feature_data_2017.describe()

,parcelid,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,calculatedfinishedsquarefeet,latitude,longitude,lotsizesquarefeet,yearbuilt,structuretaxvaluedollarcnt
count,2.985217e+06,2.982272e+06,1.941395e+06,2.868061e+06,2.940120e+06,2.982285e+06,2.982285e+06,2.712511e+06,2.937384e+06,2.938753e+06
mean,1.332586e+07,3.093362e+00,6.280822e+00,2.303826e+00,1.831455e+03,3.400131e+07,-1.182017e+08,2.260376e+04,1.964438e+03,1.781429e+05
std,7.909966e+06,1.271569e+00,1.729923e+00,1.003243e+00,1.954198e+03,2.435157e+05,3.455918e+05,2.499836e+05,2.364428e+01,4.600503e+05
min,1.071172e+07,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.332439e+07,-1.194758e+08,1.000000e+02,1.801000e+03,1.000000e+00
25%,1.164371e+07,2.000000e+00,5.000000e+00,2.000000e+00,1.215000e+03,3.382740e+07,-1.183929e+08,5.683000e+03,1.950000e+03,7.766600e+04
50%,1.254509e+07,3.000000e+00,6.000000e+00,2.000000e+00,1.574000e+03,3.400807e+07,-1.181721e+08,7.000000e+03,1.963000e+03,1.270660e+05
75%,1.409712e+07,4.000000e+00,8.000000e+00,3.000000e+00,2.140000e+03,3.416186e+07,-1.179489e+08,9.893000e+03,1.981000e+03,2.040000e+05
max,1.696019e+08,2.500000e+01,1.200000e+01,3.200000e+01,9.525760e+05,3.481965e+07,-1.175543e+08,3.710005e+08,2.016000e+03,2.553212e+08

In [14]:
# Read the training data
df_train16 = pd.read_csv('train_2016_v2.csv', na_values=['NA'])
train_2016 = df_train16
print(train_2016.shape) # Total size : (90275, 3)

df_train17 = pd.read_csv('train_2017.csv', na_values=['NA'])
train_2017 = df_train17
print(train_2017.shape) # Total size : (77613, 3)

train_2017.head()

FileNotFoundError: File b'train_2016_v2.csv' does not exist

In [ ]:
# Combine the feature data and training data
model_dataset_2016 = pd.merge(feature_data_2016, train_2016, on='parcelid')
model_dataset_2017 = pd.merge(feature_data_2017, train_2017, on='parcelid')

# Fill in missing feature data with mean values
model_dataset_filled_2016 = model_dataset_2016.fillna(model_dataset_2016.mean())
model_dataset_filled_2017 = model_dataset_2017.fillna(model_dataset_2017.mean())

In [ ]:
model_dataset_filled_2016.head()

#model_dataset_filled_2017.head()

In [ ]:
# Temporary #
# List unique values in the parcelid column
unique_val = model_dataset_filled_2016.parcelid.unique()
print(model_dataset_filled_2016.shape)
print(unique_val.shape)

unique_val = model_dataset_filled_2017.parcelid.unique()
print(model_dataset_filled_2017.shape)
print(unique_val.shape)

In [ ]:
model_dataset = [model_dataset_filled_2016, model_dataset_filled_2017]
model_dataset = pd.concat(model_dataset, ignore_index=True)

#model_dataset.describe()
model_dataset.iloc[90273:90283,:]

In [ ]:
# Temporary #
# Plot. Histogram
num_bins = 10
ax = plt.subplot()
n, bins, patches = ax.hist(model_dataset_filled_2016.buildingqualitytypeid, num_bins)

ax.set_xlabel('x', fontsize=12)
ax.set_ylabel('y', fontsize=12)
ax.set_title('Histogram', fontsize=12)

plt.tight_layout()
plt.show()

In [ ]:
# Preprocessing
model_dataset_norm = model_dataset

# Normalize the features with skewed distributions
model_dataset_norm.calculatedbathnbr = np.log(model_dataset_norm.calculatedbathnbr)
model_dataset_norm.calculatedfinishedsquarefeet = np.log(model_dataset_norm.calculatedfinishedsquarefeet)
model_dataset_norm.lotsizesquarefeet = np.log(model_dataset_norm.lotsizesquarefeet)
#model_dataset_norm.roomcnt = np.log(model_dataset_norm.roomcnt)
model_dataset_norm.structuretaxvaluedollarcnt = np.log(model_dataset_norm.structuretaxvaluedollarcnt)

model_dataset_norm.head()

In [ ]:
model_dataset_norm.describe()

In [ ]:
from sklearn import preprocessing

model_dataset_norm.loc[:,'bedroomcnt':'structuretaxvaluedollarcnt'] = \
 preprocessing.scale(model_dataset_norm.loc[:,'bedroomcnt':'structuretaxvaluedollarcnt'])

model_dataset_norm.describe()

In [ ]:
model_dataset_norm.head()

In [ ]:
feature_list = ['parcelid','bedroomcnt','buildingqualitytypeid',
                'calculatedbathnbr','calculatedfinishedsquarefeet',
                'lotsizesquarefeet',#'roomcnt',
                'yearbuilt','structuretaxvaluedollarcnt','transactiondate']

scoring_dataset = model_dataset_norm[feature_list]

desirability_score = pd.DataFrame(scoring_dataset.bedroomcnt
 - scoring_dataset.buildingqualitytypeid
 + scoring_dataset.calculatedbathnbr
 + scoring_dataset.calculatedfinishedsquarefeet
 + scoring_dataset.lotsizesquarefeet
 + scoring_dataset.yearbuilt
 + scoring_dataset.structuretaxvaluedollarcnt, columns=['score'])

#desirability_score.describe()
desirability_score.head()

In [ ]:
feature_list = ['parcelid','bedroomcnt','buildingqualitytypeid',
                'calculatedbathnbr','calculatedfinishedsquarefeet',
                'lotsizesquarefeet',#'roomcnt',
                'yearbuilt','transactiondate']

scoring_dataset = model_dataset_norm[feature_list]

desirability_score = pd.DataFrame(scoring_dataset.bedroomcnt
 - scoring_dataset.buildingqualitytypeid
 + scoring_dataset.calculatedbathnbr
 + scoring_dataset.calculatedfinishedsquarefeet
 + scoring_dataset.lotsizesquarefeet
 + scoring_dataset.yearbuilt, columns=['score'])

#desirability_score.describe()
desirability_score.head()

In [ ]:
# Temporary #
# Plot. Histogram
num_bins = 10
ax = plt.subplot()
n, bins, patches = ax.hist(desirability_score.score, num_bins)

ax.set_xlabel('x', fontsize=12)
ax.set_ylabel('y', fontsize=12)
ax.set_title('Histogram', fontsize=12)

plt.tight_layout()
plt.show()

In [ ]:
# Append the desirability score to the dataset
scoring_result = pd.concat([scoring_dataset, desirability_score], axis=1)

scoring_result.head()

In [ ]:
# Sort based on scores
scoring_result_ordered = scoring_result.sort_values('score', ascending=False)

scoring_result_ordered.head()

In [ ]:
# Get the ten most desirable houses in the dataset
most_desirables = scoring_result_ordered[:10]
most_desirables = scoring_result_ordered.head(n=10)

print(most_desirables['buildingqualitytypeid'].mean())
most_desirables

In [ ]:
# Get the ten least desirable houses in the dataset
least_desirables = scoring_result_ordered[-10:]
least_desirables = scoring_result_ordered.tail(n=10)

print(least_desirables['buildingqualitytypeid'].mean())
least_desirables

The scoring function is a linear combination of feature values. The variables used for the scoring function are